version: '3'

services:
    rsshub:
        image: theosun/rsshub
        restart: always
        ports:
            - '1200:1200'
        environment:
            NODE_ENV: production
            CACHE_TYPE: redis
            PRE_FETCH: 'true'
            LOGGER_LEVEL: 'warn'
            CACHE_EXPIRE: 300 # 5 minutes
            CACHE_CONTENT_EXPIRE: 7200 # 2 hours
            REDIS_URL: 'redis://redis:6379/'
            PUPPETEER_WS_ENDPOINT: 'ws://browserless:3000'
        depends_on:
            - redis
            - browserless

    browserless:
        image: browserless/chrome
        restart: always

    redis:
        image: redis:alpine
        restart: always
        volumes:
            - redis-data:/data

volumes:
    redis-data:
