name: unit-test

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    services:
      redis:
        image: redis
        ports:
          - 6379/tcp
        options: --entrypoint redis-server

    strategy:
      matrix:
        node-version: [18.x]

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'

    - run: npm i -g pnpm
    - run: pnpm i
    - run: pnpm test
      env:
        REDIS_URL: redis://localhost:${{ job.services.redis.ports[6379] }}/

    - name: Coverage
      uses: codecov/codecov-action@v1
