name: unit-test

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-20.04

    services:
      redis:
        image: redis
        ports:
          - 6379/tcp
        options: --entrypoint redis-server

    strategy:
      matrix:
        node-version: [18.x]

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Cache node modules
      uses: actions/cache@v1
      env:
        cache-name: cache-node-modules
      with:
        path: ~/.npm
        key: ${{ runner.os }}-${{ env.cache-name }}-${{ matrix.node-version }}-${{ hashFiles('**/package-lock.json') }}
    - run: npm install
    - run: npm run test
      env:
        REDIS_URL: redis://localhost:${{ job.services.redis.ports[6379] }}/
    - name: Coverage
      uses: codecov/codecov-action@v1
