name: unit-test

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-18.04

    services:
      redis:
        image: redis
        ports:
          - 6379/tcp
        options: --entrypoint redis-server

    strategy:
      matrix:
        node-version: [10.x, 12.x]

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm install
    - run: npm run jest
      env:
        REDIS_URL: redis://localhost:${{ job.services.redis.ports[6379] }}/
    - name: Coverage
      uses: codecov/codecov-action@v1
