name: unit-test

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    services:
      redis:
        image: redis
        ports:
          - 6379/tcp
        options: --entrypoint redis-server

    strategy:
      matrix:
        node-version: [20.x]

    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'

    - run: npm ci
    - run: npm test
      env:
        REDIS_URL: redis://localhost:${{ job.services.redis.ports[6379] }}/

    - name: Coverage
      uses: codecov/codecov-action@v1
